/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215753;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Win_loseTest {
    @Test void win_loseTest(){
        Win_lose ju = new Win_lose();
        String result = "あなたの勝ち！！";
        int playerPoint  = 21;
        int enemyPoint = 17;
        assertEquals(result,ju.judge(playerPoint,enemyPoint));
    }
}
